In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
data = pd.read_csv('/content/drive/MyDrive/機器學習colaboratory/期末/titanic.csv')
data

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
from sklearn.model_selection import train_test_split #載入切割套件,75%訓練集,25%測試集
from sklearn.model_selection import cross_val_score #載入準確率套件
from sklearn.feature_extraction.text import TfidfVectorizer #載入轉換
from sklearn.linear_model._logistic import LogisticRegression #載入羅吉斯回歸模型

# LogisticRegression

In [8]:
"""資料都填上平均值"""
age_mean = data['age'].mean()
data['age'] = data['age'].fillna(age_mean)
fare_mean = data['fare'].mean()
data['fare'] = data['fare'].fillna(fare_mean)
"""登船港口embarked 轉換"""
x_OneHot_data = pd.get_dummies(data=data,columns=["embarked" ])

In [9]:
feature_name = ['age', 'fare', 'survived']

In [10]:
X = data[feature_name]
X

            age        fare  survived
0     29.000000  211.337500       1.0
1      0.916700  151.550000       1.0
2      2.000000  151.550000       0.0
3     30.000000  151.550000       0.0
4     25.000000  151.550000       0.0
...         ...         ...       ...
1305  29.881135   14.454200       0.0
1306  26.500000    7.225000       0.0
1307  27.000000    7.225000       0.0
1308  29.000000    7.875000       0.0
1309  29.881135   33.295479       NaN

[1310 rows x 3 columns]

In [11]:
y = data ['pclass']
y

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
1305    3.0
1306    3.0
1307    3.0
1308    3.0
1309    NaN
Name: pclass, Length: 1310, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split
X_train_raw,X_test_raw,y_train,y_test=train_test_split(data["survived"].astype("U"),data["age"].astype("U")) #超參數

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect=TfidfVectorizer()
X_train=vect.fit_transform(X_train_raw)
print(X_train[10])

In [15]:
from sklearn.linear_model import LogisticRegression
cls=LogisticRegression()
cls.fit(X_train,y_train)

LogisticRegression()

In [16]:
from sklearn.model_selection import cross_val_score
score1=cross_val_score(cls,X_train,y_train,cv=5,scoring="accuracy")

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,

In [17]:
print("accuracies:%s"%score1)
print("mean accuracy:%s"%np.mean(score1))

accuracies:[0.19796954 0.1928934  0.19387755 0.19897959 0.19897959]
mean accuracy:0.19653993577126286

# 貝氏

In [20]:
df = data

In [21]:
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.000000,0.0,0.0,24160,211.337500,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.916700,1.0,2.0,113781,151.550000,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.000000,1.0,2.0,113781,151.550000,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1.0,2.0,113781,151.550000,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1.0,2.0,113781,151.550000,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,29.881135,1.0,0.0,2665,14.454200,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.500000,0.0,0.0,2656,7.225000,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.000000,0.0,0.0,2670,7.225000,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.000000,0.0,0.0,315082,7.875000,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,29.881135,NaN,NaN,NaN,33.295479,NaN,NaN,NaN,NaN,NaN

In [ ]:
feature = data.data
reasult = df.target

In [ ]:
from sklearn.model_selection import train_test_split

# 決策樹

In [25]:
from sklearn.model_selection import train_test_split
X_train_raw,X_test_raw,y_train,y_test=train_test_split(df["survived"].astype("U"),df["age"].astype("U"))

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
clf = DecisionTreeClassifier()

In [28]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
clf.score(X_test_raw,y_test)

# 隨機森林

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [35]:
clf=RandomForestClassifier(n_estimators=100,criterion="entropy")

In [38]:
clf.fit(X_train,y_train)

ValueError: ignored

In [ ]:
clf.score(X_test,y_test)

In [ ]:
print(clf.feature_importances_)

In [ ]:
import matplotlib.pyplot as plt
from sklearn import tree

In [ ]:
tree.plot_tree(clf.estimators_[0],feature_names=iris.feature_names,class_names=iris.target_names,filled=True)

In [ ]:
RFC = RandomForestClassifier( n_estimators = 1000,
                              min_samples_split = 20,
                              min_samples_leaf = 1,
                              oob_score = True,
                              random_state = 1,
                              n_jobs = -1 )

# SVM

In [44]:
from sklearn.svm import SVC
clf = SVC(kernel='linear')

In [48]:
X_train_raw,X_test_raw,y_train,y_test=train_test_split(data["survived"].astype("U"),data["age"].astype("U")) #超參數

In [ ]:
clf.fit(X_train_raw,y_train)

In [ ]:
clf.score(X_test_raw,y_test)

In [ ]:
clf2=SVC(kernel='rbf')
clf2.fit(X_train_raw,y_train)
clf2.score(X_test_raw,y_test)

In [ ]:
clf3=SVC(kernel='poly')
clf3.fit(X_train,y_train)
clf3.score(X_test,y_test)